name: Test
on: 
  push:
  pull_request:
  workflow_dispatch:
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  
  - name: Download File Action
    uses: Minionguyjpro/Download-File-Action@v1
    with:
      url: https://example.com/
      path: ./
